# Generated by Django 4.0.4 on 2022-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_alter_comment_comment_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
